heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch1:9200
    - http://elasticsearch2:9200
    - http://kibana:5601
    
output.elasticsearch:
  hosts: ["elasticsearch1:9200", "elasticsearch2:9200"]
  template.name: "heartbeat"
  template.path: "heartbeat.template.json"
  template.overwrite: false